BEGIN;

-- 在阿里云 RDS PostgreSQL 控制台执行。
-- 执行前请先创建 RDS 备份或快照。
-- 本脚本只创建 OAuth 新表，并向现有 mcp.clients JSON 增加 chatgpt 权限配置。
-- 它不会创建 OAuth client secret；建表成功后仍需在应用服务器运行 provision-client。

CREATE TABLE IF NOT EXISTS mcp_oauth_client (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(128) NOT NULL,
    client_secret_ciphertext TEXT NOT NULL,
    token_endpoint_auth_method VARCHAR(32) NOT NULL,
    client_name VARCHAR(128) NOT NULL,
    mcp_profile_name VARCHAR(128) NOT NULL,
    redirect_uris_json TEXT NOT NULL,
    grant_types_json TEXT NOT NULL,
    scope VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_mcp_oauth_client_auth_method
        CHECK (token_endpoint_auth_method IN ('client_secret_basic', 'client_secret_post'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_mcp_oauth_client_client_id
    ON mcp_oauth_client (client_id);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_client_mcp_profile_name
    ON mcp_oauth_client (mcp_profile_name);

CREATE TABLE IF NOT EXISTS mcp_oauth_authorization_request (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id_hash VARCHAR(64) NOT NULL,
    client_id INTEGER NOT NULL REFERENCES mcp_oauth_client (id),
    redirect_uri TEXT NOT NULL,
    state TEXT,
    scope VARCHAR(255) NOT NULL,
    resource TEXT NOT NULL,
    code_challenge VARCHAR(128) NOT NULL,
    code_challenge_method VARCHAR(16) NOT NULL,
    csrf_hash VARCHAR(64) NOT NULL,
    failed_attempts INTEGER NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_mcp_oauth_request_pkce_method CHECK (code_challenge_method = 'S256')
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_mcp_oauth_authorization_request_request_id_hash
    ON mcp_oauth_authorization_request (request_id_hash);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_authorization_request_client_id
    ON mcp_oauth_authorization_request (client_id);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_authorization_request_expires_at
    ON mcp_oauth_authorization_request (expires_at);

CREATE TABLE IF NOT EXISTS mcp_oauth_authorization_code (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash VARCHAR(64) NOT NULL,
    client_id INTEGER NOT NULL REFERENCES mcp_oauth_client (id),
    user_id INTEGER NOT NULL REFERENCES user_account (id),
    redirect_uri TEXT NOT NULL,
    scope VARCHAR(255) NOT NULL,
    resource TEXT NOT NULL,
    code_challenge VARCHAR(128) NOT NULL,
    code_challenge_method VARCHAR(16) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_mcp_oauth_code_pkce_method CHECK (code_challenge_method = 'S256')
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_mcp_oauth_authorization_code_code_hash
    ON mcp_oauth_authorization_code (code_hash);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_authorization_code_client_id
    ON mcp_oauth_authorization_code (client_id);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_authorization_code_user_id
    ON mcp_oauth_authorization_code (user_id);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_authorization_code_expires_at
    ON mcp_oauth_authorization_code (expires_at);

CREATE TABLE IF NOT EXISTS mcp_oauth_token (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    token_type VARCHAR(16) NOT NULL,
    client_id INTEGER NOT NULL REFERENCES mcp_oauth_client (id),
    user_id INTEGER NOT NULL REFERENCES user_account (id),
    mcp_profile_name VARCHAR(128) NOT NULL,
    scope VARCHAR(255) NOT NULL,
    resource TEXT NOT NULL,
    refresh_family_id VARCHAR(64),
    parent_token_id INTEGER REFERENCES mcp_oauth_token (id),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_mcp_oauth_token_type CHECK (token_type IN ('access', 'refresh'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_mcp_oauth_token_token_hash
    ON mcp_oauth_token (token_hash);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_token_token_type
    ON mcp_oauth_token (token_type);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_token_client_id
    ON mcp_oauth_token (client_id);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_token_user_id
    ON mcp_oauth_token (user_id);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_token_mcp_profile_name
    ON mcp_oauth_token (mcp_profile_name);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_token_refresh_family_id
    ON mcp_oauth_token (refresh_family_id);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_token_expires_at
    ON mcp_oauth_token (expires_at);
CREATE INDEX IF NOT EXISTS ix_mcp_oauth_token_revoked_at
    ON mcp_oauth_token (revoked_at);

DO $oauth_profile$
DECLARE
    current_value JSONB;
    current_chatgpt JSONB;
    desired_chatgpt CONSTANT JSONB := $json$
    {
      "enabled": true,
      "auth_modes": ["oauth"],
      "allowed_tools": [
        "market_radar.search_source_items",
        "track_discovery.get_track_detail",
        "stock_analysis.get_stock_profile",
        "report_library.read_report_content",
        "portfolio.get_overview",
        "report_library.upload_markdown_report",
        "knowledge_base.get_researcher_profile",
        "knowledge_base.upload_research_feedback"
      ],
      "max_result_limit": 50,
      "local_only": false,
      "note": "ChatGPT OAuth access"
    }
    $json$::JSONB;
BEGIN
    SELECT config_value::JSONB
      INTO current_value
      FROM system_config
     WHERE config_key = 'mcp.clients'
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'system_config.mcp.clients does not exist; refusing to create a replacement';
    END IF;
    IF jsonb_typeof(current_value) <> 'object' THEN
        RAISE EXCEPTION 'system_config.mcp.clients must be a JSON object';
    END IF;

    current_chatgpt := current_value -> 'chatgpt';
    IF current_chatgpt IS NULL THEN
        UPDATE system_config
           SET config_value = jsonb_set(current_value, '{chatgpt}', desired_chatgpt, true)::TEXT,
               updated_at = CURRENT_TIMESTAMP
         WHERE config_key = 'mcp.clients';
    ELSIF current_chatgpt <> desired_chatgpt THEN
        RAISE EXCEPTION 'mcp.clients.chatgpt already exists with different settings; refusing to overwrite it';
    END IF;
END
$oauth_profile$;

COMMIT;

-- 验收：应返回 4 行表名，以及不包含 Codex Token 的 chatgpt 配置。
SELECT table_name
  FROM information_schema.tables
 WHERE table_schema = current_schema()
   AND table_name IN (
       'mcp_oauth_client',
       'mcp_oauth_authorization_request',
       'mcp_oauth_authorization_code',
       'mcp_oauth_token'
   )
 ORDER BY table_name;

SELECT config_value::JSONB -> 'chatgpt' AS chatgpt_oauth_profile
  FROM system_config
 WHERE config_key = 'mcp.clients';
