import fs from "node:fs";
import assert from "node:assert/strict";

const page = fs.readFileSync(new URL("./PortfolioPage.tsx", import.meta.url), "utf8");
const chartTheme = fs.readFileSync(new URL("../../components/charts/chartTheme.ts", import.meta.url), "utf8");

assert.match(page, /新建组合/);
assert.match(page, /重命名/);
assert.match(page, /删除组合/);
assert.match(page, /刷新当前组合/);
assert.match(page, /新增持仓/);
assert.match(page, /请选择标的/);
assert.match(page, /股数/);
assert.match(page, /当日盈亏/);
assert.match(page, /当日涨跌幅/);
assert.match(page, /Popconfirm/);
assert.match(page, /searchStocks/);
assert.match(page, /getPortfolioOverview/);
assert.match(page, /listPortfolioValueSnapshots/);
assert.match(page, /ChartCard/);
assert.match(page, /市值占比/);
assert.match(page, /组合市值曲线/);
assert.match(page, /标的市值占比/);
assert.match(page, /legendFormatter/);
assert.match(page, /lightAllocationColors/);
assert.match(page, /darkAllocationColors/);
assert.match(page, /allocationColorsForMode/);
assert.match(page, /持仓市值/);
assert.match(page, /graphic/);
assert.match(page, /center: \["63%", "52%"\]/);
assert.match(chartTheme, /return "transparent"/);
assert.match(page, /现金余额/);
assert.match(page, /资金流水/);
assert.match(page, /组合复盘/);
assert.match(page, /getPortfolioReviewPerformance/);
assert.match(page, /沪深300/);
assert.match(page, /收益率曲线/);
assert.match(page, /盈亏日历/);
assert.match(page, /当月/);
assert.match(page, /当年/);
assert.match(page, /有效记录以来/);
assert.match(page, /reviewLineOption/);
assert.match(page, /reviewCalendarOption/);
assert.match(page, /renderOverview/);
assert.match(page, /renderPositions/);
assert.match(page, /renderTrades/);
assert.match(page, /renderReview/);
assert.doesNotMatch(page, /暂无组合复盘/);
assert.doesNotMatch(page, /组合分类维度/);
assert.doesNotMatch(page, /allocationColumns/);
