import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const navigation = readFileSync("invest_assistant/ui/web/src/app/navigation.tsx", "utf8");
const page = readFileSync("invest_assistant/ui/web/src/pages/dashboard/DashboardPage.tsx", "utf8");
const globalCss = readFileSync("invest_assistant/ui/web/src/styles/global.css", "utf8");
const todaySection = page.match(/function TodayDashboardSection\(\)[\s\S]*?function OperationsPanelSection/)?.[0] || "";
const operationsSection = page.match(/function OperationsPanelSection\(\)[\s\S]*?function ReportTable/)?.[0] || "";
const latestReportsSection = page.match(/function LatestReportsSection\(\)[\s\S]*?export function DashboardPage/)?.[0] || "";

function cssRule(selector) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const matches = [...globalCss.matchAll(new RegExp(`${escaped}\\s*\\{([^}]*)\\}`, "g"))];
  return matches.at(-1)?.[1] || "";
}

assert.match(navigation, /key:\s*"dashboard",\s*label:\s*"工作台"/);
assert.doesNotMatch(navigation, /key:\s*"dashboard",\s*label:\s*"总览"/);
assert.doesNotMatch(navigation, /primaryNavItems[\s\S]*label:\s*"今日看板"[\s\S]*moduleTabs/);

assert.match(navigation, /dashboard:\s*\[[\s\S]*label:\s*"今日看板"[\s\S]*label:\s*"操作面板"[\s\S]*label:\s*"最新报告"[\s\S]*\]/);

assert.match(page, /<PageHeader\s+title="工作台"/);
assert.doesNotMatch(page, /<PageHeader\s+title="今日看板"/);
assert.match(page, /<ModuleTabs\s+activeKey=\{activeTab\}\s+items=\{moduleTabs\.dashboard\}/);

assert.match(page, /title="新增"/);
assert.match(page, /title="活跃"/);
assert.match(page, /title="统计"/);
assert.match(page, /title="待办入口"/);
assert.match(page, /title="AI 控制面板"/);
assert.match(page, /workbench-action-grid/);
assert.doesNotMatch(page, /title="待办队列摘要"/);
assert.match(todaySection, /title="最近执行记录"/);
assert.match(todaySection, /市场与组合/);
assert.match(todaySection, /className="workbench-market-card"/);
assert.match(todaySection, /组合表现/);
assert.doesNotMatch(todaySection, /组合今日表现/);
assert.match(todaySection, /workbench-market-meta/);
assert.match(todaySection, /formatShortDateTime/);
assert.match(todaySection, /formatShortTime/);
assert.match(todaySection, /workbench-index-icon/);
assert.match(todaySection, /indexBadgeText/);
assert.match(todaySection, /workbench-portfolio-card/);
assert.match(todaySection, /刷新行情/);
assert.match(todaySection, /market_indices/);
assert.match(todaySection, /portfolio_today/);
assert.match(todaySection, /refreshWorkbenchMarket/);
assert.doesNotMatch(todaySection, /refreshPortfolioQuotes/);
assert.match(todaySection, /getWorkbenchToday/);
assert.doesNotMatch(todaySection, /getSourceItemDailyStats/);
assert.doesNotMatch(todaySection, /getAiLogStats/);
assert.doesNotMatch(todaySection, /getMarketOverview/);
assert.doesNotMatch(todaySection, /getHotwordStats/);
assert.doesNotMatch(todaySection, /listStockPool/);
assert.doesNotMatch(todaySection, /listTracks/);
assert.doesNotMatch(todaySection, /listJobs/);
assert.doesNotMatch(todaySection, /listRunRequests/);
assert.doesNotMatch(todaySection, /getTrackDashboard/);
assert.doesNotMatch(todaySection, /listAiTagSuggestions/);
assert.doesNotMatch(todaySection, /listAllStockMaterials/);
assert.doesNotMatch(todaySection, /getAlertEventStats/);
assert.doesNotMatch(todaySection, /listSourceItems\(\{\s*limit:\s*200\s*\}\)/);
assert.doesNotMatch(todaySection, /getAiLogs/);
assert.doesNotMatch(todaySection, /listMarketTags/);
assert.doesNotMatch(globalCss, /workbench-index-tile::before/);
assert.doesNotMatch(globalCss, /:has\(\.workbench-index-change/);
assert.match(globalCss, /workbench-index-icon/);
assert.match(cssRule(".workbench-index-tile"), /border:\s*1px solid var\(--ll-border-soft\);/);
assert.match(cssRule(".workbench-index-tile"), /background:\s*var\(--ll-panel-subtle\);/);
assert.doesNotMatch(globalCss, /\[data-theme="dark"\]\s+\.workbench-index-tile/);
assert.match(cssRule(".workbench-market-card .ant-card-head"), /border-bottom-color:\s*var\(--ll-border\)\s*!important;/);
assert.match(cssRule(".workbench-market-card .ant-card-head"), /box-shadow:\s*inset 0 -1px 0 var\(--ll-border\);/);
assert.match(cssRule(".workbench-portfolio-today"), /gap:\s*0;/);
assert.match(cssRule(".workbench-portfolio-card"), /border:\s*1px solid var\(--ll-border-soft\);/);
assert.match(cssRule(".workbench-portfolio-card"), /background:\s*var\(--ll-panel-subtle\);/);
assert.doesNotMatch(cssRule(".workbench-portfolio-total"), /background:/);
assert.doesNotMatch(cssRule(".workbench-portfolio-stats div"), /background:/);
assert.match(operationsSection, /getWorkbenchToday/);
assert.doesNotMatch(operationsSection, /getTrackDashboard/);
assert.doesNotMatch(operationsSection, /listAiTagSuggestions/);
assert.doesNotMatch(operationsSection, /listAllStockMaterials/);
assert.doesNotMatch(operationsSection, /getAlertEventStats/);
assert.doesNotMatch(operationsSection, /listJobs/);
assert.doesNotMatch(operationsSection, /title="最近执行记录"/);
assert.doesNotMatch(page, /getTrackDashboard/);
assert.doesNotMatch(page, /常用网页快捷入口/);
assert.doesNotMatch(page, /待办处理入口/);
assert.doesNotMatch(page, /AI 操作按钮/);
assert.match(page, /workbench-report-list/);
assert.match(page, /import \{ DataPanel \} from "\.\.\/\.\.\/components\/common\/DataPanel"/);
assert.match(latestReportsSection, /<DataPanel/);
assert.doesNotMatch(page, /workbench-report-table/);
assert.match(page, /\{\s*label:\s*"赛道",\s*value:\s*"track"\s*\}/);
assert.match(page, /\{\s*label:\s*"标的",\s*value:\s*"stock"\s*\}/);
